# Generated by Django 6.0.3 on 2026-04-19 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paros_app', '0002_bitacoraparo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(blank=True, max_length=100, verbose_name='Equipo')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha')),
                ('turno', models.IntegerField(choices=[(1, 'Turno 1'), (2, 'Turno 2')], verbose_name='Turno')),
                ('hora_inicio', models.TimeField(verbose_name='Hora inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora fin')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_produccion', to='paros_app.area', verbose_name='Área')),
            ],
            options={
                'verbose_name': 'Registro de producción',
                'verbose_name_plural': 'Registros de producción',
                'ordering': ['-fecha', 'area', 'equipo', 'turno'],
                'unique_together': {('area', 'equipo', 'fecha', 'turno')},
            },
        ),
    ]
