# Generated by Django 6.0.3 on 2026-04-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paros_app', '0003_registroproduccion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroproduccion',
            options={'ordering': ['-fecha', 'area', 'orden', 'turno', 'equipo'], 'verbose_name': 'Registro de producción', 'verbose_name_plural': 'Registros de producción'},
        ),
        migrations.AddField(
            model_name='registroproduccion',
            name='orden',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden'),
        ),
    ]
