# Generated by Django 6.0.3 on 2026-04-21 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paros_app', '0004_alter_registroproduccion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicador', models.CharField(choices=[('downtime', 'Downtime %'), ('disponibilidad', 'Disponibilidad %'), ('mttr', 'MTTR (min)'), ('mtbf', 'MTBF (h)')], max_length=20, verbose_name='Indicador')),
                ('valor', models.FloatField(verbose_name='Valor objetivo')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='paros_app.area', verbose_name='Área')),
            ],
            options={
                'verbose_name': 'Target de indicador',
                'verbose_name_plural': 'Targets de indicadores',
                'ordering': ['area', 'indicador'],
                'unique_together': {('area', 'indicador')},
            },
        ),
    ]
