# Generated by Django 6.0.3 on 2026-04-22 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paros_app', '0005_targetindicador'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccionDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('indicador', models.CharField(blank=True, choices=[('dt', 'Downtime'), ('mttr', 'MTTR'), ('mtbf', 'MTBF'), ('dt-mttr', 'Downtime - MTTR'), ('dt-mtbf', 'Downtime - MTBF'), ('mttr-mtbf', 'MTTR - MTBF'), ('dt-mttr-mtbf', 'Downtime - MTTR - MTBF')], max_length=20)),
                ('falla', models.CharField(blank=True, max_length=200)),
                ('cont_accion', models.CharField(blank=True, max_length=100)),
                ('cont_fecha_inicio', models.DateField(blank=True, null=True)),
                ('cont_fecha_fin', models.DateField(blank=True, null=True)),
                ('cont_estatus', models.CharField(choices=[('p', 'Pendiente'), ('e', 'En proceso'), ('c', 'Cerrada')], default='p', max_length=1)),
                ('corr_accion', models.CharField(blank=True, max_length=100)),
                ('corr_fecha_inicio', models.DateField(blank=True, null=True)),
                ('corr_fecha_fin', models.DateField(blank=True, null=True)),
                ('corr_estatus', models.CharField(choices=[('p', 'Pendiente'), ('e', 'En proceso'), ('c', 'Cerrada')], default='p', max_length=1)),
                ('prev_accion', models.CharField(blank=True, max_length=100)),
                ('prev_fecha_inicio', models.DateField(blank=True, null=True)),
                ('prev_fecha_fin', models.DateField(blank=True, null=True)),
                ('prev_estatus', models.CharField(choices=[('p', 'Pendiente'), ('e', 'En proceso'), ('c', 'Cerrada')], default='p', max_length=1)),
                ('responsable', models.CharField(blank=True, max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_dia', to='paros_app.area')),
            ],
            options={
                'verbose_name': 'Acción por día',
                'verbose_name_plural': 'Acciones por día',
                'ordering': ['-fecha'],
                'unique_together': {('area', 'fecha')},
            },
        ),
    ]
