# Generated by Django 6.0.3 on 2026-04-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paros_app', '0006_acciondia'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='acciondia',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='acciondia',
            name='equipo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Equipo'),
        ),
        migrations.AlterUniqueTogether(
            name='acciondia',
            unique_together={('area', 'equipo', 'fecha', 'indicador')},
        ),
    ]
