# Generated by Django 6.0.3 on 2026-04-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paros_app', '0007_alter_acciondia_unique_together_acciondia_equipo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acciondia',
            old_name='falla',
            new_name='problema',
        ),
        migrations.AlterField(
            model_name='acciondia',
            name='equipo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Equipo'),
        ),
    ]
