# Generated by Django 6.0.3 on 2026-04-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('paros_app', '0004_alter_registroproduccion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='areas_produccion',
            field=models.ManyToManyField(blank=True, related_name='usuarios_produccion', to='paros_app.area', verbose_name='Áreas de tiempo de producción'),
        ),
    ]
